{ errors: [],
  warnings: [],
  rowNum: 13,
  auto_expire_participants: '1',
  all_day: '0',
  visibility: 0,
  start_date: '2023-01-01',
  start_time: '10:00 AM',
  meet_time: '9:45 AM',
  group: 'A',
  route_ids: [ '17166902' ],
  organizer_names: [],
  name: 'Sun A (1/1 10:00) [0] SCP - Seascape/Corralitos',
  location: 'Seascape County Park',
  address: 'Address: Seascape County Park, Sumner Ave, Aptos, CA 95003',
  desc: 'Ride Leader: To Be Determined\n\n    Address: Seascape County Park, Sumner Ave, Aptos, CA 95003\n          \nArrive 9:45 AM for a 10:00 AM rollout.\n  \nAll participants are assumed to have read and agreed to the clubs ride policy: https://scccc.clubexpress.com/content.aspx?page_id=22&club_id=575722&module_id=137709\n  \nNote: In a browser use the "Go to route" link below to open up the route.',
  organizer_tokens: [ '4733240' ] }